-- RETRIEVE ALL EMPLOYEES WHOSE ADDRESS IS IN ELGIN,IL
SELECT * FROM EMPLOYEES
WHERE ADDRESS LIKE '%ELGIN,IL%';

-- RETRIEVE ALL EMPLOYEES WHO WERE BORN DURING THE 1970'S.
SELECT * FROM EMPLOYEES
WHERE B_DATE LIKE '197%';

-- RETRIEVE ALL EMPLOYEES IN DEPARTMENT 5 WHOSE SALARY IS BETWEEN
-- 60000 AND 70000 
SELECT * FROM EMPLOYEES
WHERE SALARY BETWEEN 60000 AND 70000;

-- RETRIEVE A LIST OF EMPLOYEES ORDERED BY DEPARTMENT ID. 
SELECT * FROM EMPLOYEES
ORDER BY DEP_ID;

-- RETRIEVE A LIST OF EMPLOYEES ORDERED IN DESCENDING ORDER BY
-- DEPARTMENT ID AND WITHIN EACH DEPARTMENT ORDERED ALPHABETICALLY IN
-- DESCENDING ORDER BY LAST NAME.
SELECT * FROM EMPLOYEES
ORDER BY DEP_ID DESC, L_NAME DESC;

-- FOR EACH DEPARTMENT ID RETRIEVE THE NUMBER OF EMPLOYEES IN THE
-- DEPARTMENT.
SELECT DEP_ID, COUNT(*) AS NUM_EMP FROM EMPLOYEES
GROUP BY DEP_ID;

-- For each department retrieve the number of employees in the
-- department, and the average employees salary in the department.

select DEP_ID, count(*) as num_emp, avg(SALARY) as avg_salary 
from employees
group by DEP_ID;

-- Label the computed columns in the result set of Query 5B as
-- “NUM_EMPLOYEES” and “AVG_SALARY”.

select DEP_ID, count(*) as NUM_EMPLOYEES, avg(SALARY) as AVG_SALARY 
from employees
group by DEP_ID;

-- IN QUERY 5C ORDER THE RESULT SET BY AVERAGE SALARY.
SELECT DEP_ID, COUNT(*) AS NUM_EMPLOYEES, AVG(SALARY) AS AVG_SALARY 
FROM EMPLOYEES
GROUP BY DEP_ID
ORDER BY AVG_SALARY;

--IN QUERY 5D LIMIT THE RESULT TO DEPARTMENTS WITH FEWER THAN 4 EMPLOYEES.
SELECT DEP_ID, COUNT(*) AS NUM_EMPLOYEES, AVG(SALARY) AS AVG_SALARY 
FROM EMPLOYEES
GROUP BY DEP_ID
HAVING COUNT(*) < 4
ORDER BY AVG_SALARY;

-- RETRIEVE A LIST OF EMPLOYEES ORDERED BY DEPARTMENT NAME, AND WITHIN
-- EACH DEPARTMENT ORDERED ALPHABETICALLY IN DESCENDING ORDER BY LAST NAME.

SELECT *
FROM EMPLOYEES
JOIN DEPARTMENTS
ON DEP_ID = DEPT_ID_DEP
ORDER BY DEP_NAME, L_NAME DESC;
